name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # Trigger pour les releases via tags
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build -v -o ./dist/exPipeline ./...

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./dist/exPipeline

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run tests
        run: go test -v ./...

  measure:
    name: Measure Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

  document:
    name: Document with GoDoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Generate documentation
        run: |
          mkdir godoc_output
          go doc -all > godoc_output/godoc_output.txt

      - name: Archive documentation
        run: tar -czvf godoc_output.tar.gz godoc_output

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: godoc-output
          path: godoc_output.tar.gz

  security:
    name: Security Scan with Gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Install Gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec
        run: |
          gosec ./... > gosec_report.txt || true  # Scanne le projet et enregistre le rapport.

      - name: Archive Gosec report
        run: tar -czvf gosec_report.tar.gz gosec_report.txt

      - name: Upload Gosec report artifact
        uses: actions/upload-artifact@v3
        with:
          name: gosec-report
          path: gosec_report.tar.gz

  Release:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
